{
 "title": "For Pi2",
 "time": { "from": "2025-04-29T00:00:00.000Z", "to": "2025-05-12T00:00:00.000Z" },
 "panels": [
  {
   "title": "posture_status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE posture_status\n    WHEN 'Good' THEN 'Good'\n    WHEN 'Bad' THEN 'Bad'\n  END as status,\n  COUNT(*) as count\nFROM posture_log\nWHERE pi_id = 'pi1'\n  AND posture_status IN ('Good', 'Bad')\nGROUP BY status;\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Total Entries\"\nFROM posture_log\nWHERE pi_id = 'pi1';\n"
    }
   ]
  },
  {
   "title": "Good vs Bas Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', received_time) AS day,\n  COUNT(*) FILTER (WHERE posture_status = 'Good') AS good,\n  COUNT(*) FILTER (WHERE posture_status = 'Bad') AS bad\nFROM posture_log\nWHERE pi_id = 'pi1'\nGROUP BY day\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "Good posture frequency over the Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', received_time) AS day,\n  COUNT(*) AS good_postures\nFROM posture_log\nWHERE pi_id = 'pi1'\n  AND posture_status = 'Good'\nGROUP BY day\nORDER BY day;\n"
    }
   ]
  },
  {
   "title": "Neck and body angle when posture is bad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  received_time AS time,\n  neck_angle,\n  body_angle\nFROM posture_log\nWHERE pi_id = 'pi1' AND posture_status = 'Bad'\nORDER BY time;\n"
    }
   ]
  },
  {
   "title": "Bad Posture Frequency Over Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  DATE_TRUNC('day', received_time) AS day,\n  COUNT(*) AS bad_postures\nFROM posture_log\nWHERE pi_id = 'pi1' AND posture_status = 'Bad'\nGROUP BY day\nORDER BY day;\n"
    }
   ]
  }
 ]
}