version: '3.8'

services:
  posture-analyzer:
    image: shahroz90/posture-analyzer  # use existing local image only
    container_name: posture-analyzer
    volumes:
      - ./analyzed_images:/app/analyzed_images
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Europe/Helsinki
      - SUPABASE_HOST=aws-0-eu-north-1.pooler.supabase.com
      - SUPABASE_DB=postgres
      - SUPABASE_USER=postgres.yvqqpgixkwsiychmwvkc
      - SUPABASE_PASSWORD=University12@
      - SUPABASE_PORT=5432
      - SUPABASE_SSL=require
    restart: always

