{
 "title": "AGX-Worker-Node",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GPU usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "jetson_gpu_usage_percent{instance=\"192.168.1.135:9100\"}\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "AGX RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.1.135:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.1.135:9100\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "AGX CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.1.135:9100\"}[1m])) * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}