{
 "title": "Jetson_Nano1",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Jetson Nano 1 GPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "jetson_nano1_gpu_usage_percent", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Jetson nano 1 RAM Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"192.168.1.193:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"192.168.1.193:9100\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jetson Nano 1 CPU Load (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"192.168.1.193:9100\"}[1m])) * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}