{
 "title": "Master Node",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": " GPU  Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "intel_gpu_actual_frequency_mhz\n\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM Usage (%) ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "100 - ((node_memory_MemAvailable_bytes{instance=\"localhost:9100\"} * 100) / node_memory_MemTotal_bytes{instance=\"localhost:9100\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (rate(node_cpu_seconds_total{mode=\"idle\", instance=\"localhost:9100\"}[1m])) * 100)\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}