{
 "title": "Posture_Analysis_Data_From_Pi1",
 "time": { "from": "now-6M", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "posture_status",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  CASE posture_status\n    WHEN 'Good' THEN 'Good'\n    WHEN 'Bad' THEN 'Bad'\n  END as status,\n  COUNT(*) as count\nFROM posture_log\nWHERE pi_id = 'pi1'\n  AND posture_status IN ('Good', 'Bad')\nGROUP BY status;\n"
    }
   ]
  },
  {
   "title": "New panel",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT COUNT(*) AS \"Total Entries\"\nFROM posture_log\nWHERE pi_id = 'pi1';\n"
    }
   ]
  },
  {
   "title": "Good vs Bad Frequency",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH all_days AS (\n  SELECT generate_series(\n    NOW() - INTERVAL '30 days',\n    NOW(),\n    INTERVAL '1 day'\n  )::date AS day\n),\nposture_counts AS (\n  SELECT\n    DATE_TRUNC('day', received_time)::date AS day,\n    COUNT(*) FILTER (WHERE posture_status = 'Good') AS good,\n    COUNT(*) FILTER (WHERE posture_status = 'Bad') AS bad\n  FROM posture_log\n  WHERE pi_id = 'pi1'\n  GROUP BY 1\n)\nSELECT\n  a.day,\n  COALESCE(p.good, 0) AS good,\n  COALESCE(p.bad, 0) AS bad\nFROM all_days a\nLEFT JOIN posture_counts p ON a.day = p.day\nORDER BY a.day;\n"
    }
   ]
  },
  {
   "title": "Good posture frequency over the Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
   "targets": [
    {
     "rawSql": "WITH all_days AS (\n  SELECT generate_series(\n    NOW() - INTERVAL '30 days',\n    NOW(),\n    INTERVAL '1 day'\n  )::date AS day\n),\ngood_postures AS (\n  SELECT\n    DATE_TRUNC('day', received_time)::date AS day,\n    COUNT(*) AS good\n  FROM posture_log\n  WHERE pi_id = 'pi1'\n    AND posture_status = 'Good'\n  GROUP BY day\n)\nSELECT\n  a.day,\n  COALESCE(g.good, 0) AS good_postures\nFROM all_days a\nLEFT JOIN good_postures g ON a.day = g.day\nORDER BY a.day;\n"
    }
   ]
  },
  {
   "title": "Neck and body angle when posture is bad",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "rawSql": "SELECT\n  received_time AS \"time\",\n  neck_angle,\n  body_angle\nFROM posture_log\nWHERE received_time::date = CURRENT_DATE\n  AND pi_id = 'pi1'\nORDER BY received_time;\n"
    }
   ]
  },
  {
   "title": "Bad Posture Frequency Over Time",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "rawSql": "WITH all_days AS (\n  SELECT generate_series(\n    NOW() - INTERVAL '30 days',\n    NOW(),\n    INTERVAL '1 day'\n  )::date AS day\n),\nbad_postures AS (\n  SELECT\n    DATE_TRUNC('day', received_time)::date AS day,\n    COUNT(*) AS bad\n  FROM posture_log\n  WHERE pi_id = 'pi1'\n    AND posture_status = 'Bad'\n  GROUP BY day\n)\nSELECT\n  a.day,\n  COALESCE(b.bad, 0) AS bad_postures\nFROM all_days a\nLEFT JOIN bad_postures b ON a.day = b.day\nORDER BY a.day;\n"
    }
   ]
  }
 ]
}