FROM python:3.12-slim
WORKDIR /app

# Install required dependencies
RUN pip install --no-cache-dir fastapi==0.115.0 httpx==0.27.2 uvicorn==0.30.6 prometheus-api-client==0.5.4 kubernetes==30.1.0

# Copy controller script
COPY controller.py .

CMD ["python", "controller.py"]

